### ISSUE TITLE
Big Bang

### ISSUE THREAD

**Issue by NWWGIT** [jzmiller1/ExchangeConflict2016#2]
Not sure what is going on. When I try to launch big bang, I get this error:
Forming ring... [12, 13, 8, 4, 10]
Traceback (most recent call last):
  File "bigbang.py", line 216, in <module>
    u, s = universe(25, 5, 1, 1, 'common', 'normal', items)
  File "bigbang.py", line 191, in universe
    u = gen(total_systems, deadends, rings, connectivity)
  File "bigbang.py", line 85, in gen
    elements = nx.connected_component_subgraphs(G)
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'

**Comment by jzmiller1** [comment]
This was written to run on networkx version 1.11.  If you are using a newer version networkx may have removed or renamed 'connected_component_subgraphs'.
